#!/bin/bash

#DOCKER_EXEC_FLAGS="i"

# Determine whether stdout is on a terminal
#if [ -t 1 ] ; then
#    DOCKER_EXEC_FLAGS+="t"
#fi

#docker exec -$DOCKER_EXEC_FLAGS pmon python /usr/local/lib/python2.7/dist-packages/platform_ndk/nokia_cmd.py "$@"
python3 /usr/lib/python3/dist-packages/platform_ndk/nokia_cmd.py "$@"
