# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from platform_ndk import platform_ndk_pb2 as platform__ndk_dot_platform__ndk__pb2


class ChassisPlatformNdkServiceStub(object):
  """Chassis related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetModuleName = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetModuleName',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetModuleStatus = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetModuleStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetChassisType = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetChassisType',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetChassisStatus = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetChassisStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetModuleMaxPower = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetModuleMaxPower',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetMySlot = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetMySlot',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetChassisProperties = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetChassisProperties',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.GetMidplaneIP = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/GetMidplaneIP',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.IsMidplaneReachable = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/IsMidplaneReachable',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )
    self.PingMidplaneIP = channel.unary_unary(
        '/protos.platform_ndk.ChassisPlatformNdkService/PingMidplaneIP',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.FromString,
        )


class ChassisPlatformNdkServiceServicer(object):
  """Chassis related APIs
  """

  def GetModuleName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModuleStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChassisType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChassisStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModuleMaxPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMySlot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChassisProperties(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMidplaneIP(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsMidplaneReachable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PingMidplaneIP(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChassisPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetModuleName': grpc.unary_unary_rpc_method_handler(
          servicer.GetModuleName,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetModuleStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetModuleStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetChassisType': grpc.unary_unary_rpc_method_handler(
          servicer.GetChassisType,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetChassisStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetChassisStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetModuleMaxPower': grpc.unary_unary_rpc_method_handler(
          servicer.GetModuleMaxPower,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetMySlot': grpc.unary_unary_rpc_method_handler(
          servicer.GetMySlot,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetChassisProperties': grpc.unary_unary_rpc_method_handler(
          servicer.GetChassisProperties,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'GetMidplaneIP': grpc.unary_unary_rpc_method_handler(
          servicer.GetMidplaneIP,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'IsMidplaneReachable': grpc.unary_unary_rpc_method_handler(
          servicer.IsMidplaneReachable,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
      'PingMidplaneIP': grpc.unary_unary_rpc_method_handler(
          servicer.PingMidplaneIP,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqModuleInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespModuleInfoPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.ChassisPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PsuPlatformNdkServiceStub(object):
  """PSU related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPsuNum = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuNum',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuPresence = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuPresence',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuStatus = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.ShowPsuInfo = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/ShowPsuInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuMaximumPower = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuMaximumPower',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuModel = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuModel',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuSerial = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuSerial',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuOutputCurrent = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuOutputCurrent',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuOutputVoltage = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuOutputVoltage',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuOutputPower = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuOutputPower',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuTemperature = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuTemperature',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuMaxOutputVoltage = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuMaxOutputVoltage',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuMinOutputVoltage = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuMinOutputVoltage',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )
    self.GetPsuMaxTemperature = channel.unary_unary(
        '/protos.platform_ndk.PsuPlatformNdkService/GetPsuMaxTemperature',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.FromString,
        )


class PsuPlatformNdkServiceServicer(object):
  """PSU related APIs
  """

  def GetPsuNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuPresence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowPsuInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuMaximumPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuSerial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuOutputCurrent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuOutputVoltage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuOutputPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuTemperature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuMaxOutputVoltage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuMinOutputVoltage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPsuMaxTemperature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PsuPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPsuNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuNum,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuPresence': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuPresence,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'ShowPsuInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ShowPsuInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuMaximumPower': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuMaximumPower,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuModel,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuSerial': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuSerial,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuOutputCurrent': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuOutputCurrent,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuOutputVoltage': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuOutputVoltage,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuOutputPower': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuOutputPower,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuTemperature': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuTemperature,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuMaxOutputVoltage': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuMaxOutputVoltage,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuMinOutputVoltage': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuMinOutputVoltage,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
      'GetPsuMaxTemperature': grpc.unary_unary_rpc_method_handler(
          servicer.GetPsuMaxTemperature,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqPsuInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespPsuInfoPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.PsuPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ThermalPlatformNdkServiceStub(object):
  """Thermal related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetThermalCurrTemp = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalCurrTemp',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.GetThermalMinTemp = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalMinTemp',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.GetThermalMaxTemp = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalMaxTemp',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.GetThermalLowThreshold = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalLowThreshold',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.GetThermalHighThreshold = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalHighThreshold',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.GetThermalDevicesInfo = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/GetThermalDevicesInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.ShowThermalInfo = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/ShowThermalInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.UpdateThermalHwSlot = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/UpdateThermalHwSlot',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )
    self.SetThermalOffset = channel.unary_unary(
        '/protos.platform_ndk.ThermalPlatformNdkService/SetThermalOffset',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.FromString,
        )


class ThermalPlatformNdkServiceServicer(object):
  """Thermal related APIs
  """

  def GetThermalCurrTemp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermalMinTemp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermalMaxTemp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermalLowThreshold(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermalHighThreshold(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetThermalDevicesInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowThermalInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateThermalHwSlot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetThermalOffset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ThermalPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetThermalCurrTemp': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalCurrTemp,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'GetThermalMinTemp': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalMinTemp,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'GetThermalMaxTemp': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalMaxTemp,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'GetThermalLowThreshold': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalLowThreshold,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'GetThermalHighThreshold': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalHighThreshold,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'GetThermalDevicesInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetThermalDevicesInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'ShowThermalInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ShowThermalInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'UpdateThermalHwSlot': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateThermalHwSlot,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
      'SetThermalOffset': grpc.unary_unary_rpc_method_handler(
          servicer.SetThermalOffset,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqTempParamsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespTempParamsPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.ThermalPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FanPlatformNdkServiceStub(object):
  """FAN related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFanNum = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanNum',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanPresence = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanPresence',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanStatus = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanTargetSpeed = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanTargetSpeed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanActualSpeed = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanActualSpeed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanDirection = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanDirection',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanTolerance = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanTolerance',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanLedStatus = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanLedStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.SetFanTargetSpeed = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/SetFanTargetSpeed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.DisableFanAlgorithm = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/DisableFanAlgorithm',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.SetFanLedStatus = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/SetFanLedStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanTraySerialNo = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanTraySerialNo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.GetFanTrayPartNo = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/GetFanTrayPartNo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )
    self.ShowFanInfo = channel.unary_unary(
        '/protos.platform_ndk.FanPlatformNdkService/ShowFanInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.FromString,
        )


class FanPlatformNdkServiceServicer(object):
  """FAN related APIs
  """

  def GetFanNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanPresence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanTargetSpeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanActualSpeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanDirection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanTolerance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanLedStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFanTargetSpeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableFanAlgorithm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFanLedStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanTraySerialNo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFanTrayPartNo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowFanInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FanPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFanNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanNum,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanPresence': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanPresence,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanTargetSpeed': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanTargetSpeed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanActualSpeed': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanActualSpeed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanDirection': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanDirection,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanTolerance': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanTolerance,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanLedStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanLedStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'SetFanTargetSpeed': grpc.unary_unary_rpc_method_handler(
          servicer.SetFanTargetSpeed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'DisableFanAlgorithm': grpc.unary_unary_rpc_method_handler(
          servicer.DisableFanAlgorithm,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'SetFanLedStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SetFanLedStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanTraySerialNo': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanTraySerialNo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'GetFanTrayPartNo': grpc.unary_unary_rpc_method_handler(
          servicer.GetFanTrayPartNo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
      'ShowFanInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ShowFanInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqFanTrayOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespFanTrayOpsPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.FanPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LedPlatformNdkServiceStub(object):
  """LED related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLed = channel.unary_unary(
        '/protos.platform_ndk.LedPlatformNdkService/GetLed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.FromString,
        )
    self.SetLed = channel.unary_unary(
        '/protos.platform_ndk.LedPlatformNdkService/SetLed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.FromString,
        )
    self.ShowLed = channel.unary_unary(
        '/protos.platform_ndk.LedPlatformNdkService/ShowLed',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.FromString,
        )


class LedPlatformNdkServiceServicer(object):
  """LED related APIs
  """

  def GetLed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowLed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LedPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLed': grpc.unary_unary_rpc_method_handler(
          servicer.GetLed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.SerializeToString,
      ),
      'SetLed': grpc.unary_unary_rpc_method_handler(
          servicer.SetLed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.SerializeToString,
      ),
      'ShowLed': grpc.unary_unary_rpc_method_handler(
          servicer.ShowLed,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLedInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLedInfoPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.LedPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class XcvrPlatformNdkServiceStub(object):
  """SFP related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSfpEepromInfo = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpEepromInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpEepromPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.GetSfpEepromInfoPb.FromString,
        )
    self.GetSfpPresence = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpPresence',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.GetSfpStatus = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.ReqSfpReset = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/ReqSfpReset',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.GetSfpResetStatus = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpResetStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.ReqSfpLPMode = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/ReqSfpLPMode',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.GetSfpLPStatus = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpLPStatus',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.ReqSfpTxDisable = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/ReqSfpTxDisable',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )
    self.GetSfpNum = channel.unary_unary(
        '/protos.platform_ndk.XcvrPlatformNdkService/GetSfpNum',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.FromString,
        )


class XcvrPlatformNdkServiceServicer(object):
  """SFP related APIs
  """

  def GetSfpEepromInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSfpPresence(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSfpStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqSfpReset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSfpResetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqSfpLPMode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSfpLPStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqSfpTxDisable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSfpNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_XcvrPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSfpEepromInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpEepromInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpEepromPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.GetSfpEepromInfoPb.SerializeToString,
      ),
      'GetSfpPresence': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpPresence,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'GetSfpStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'ReqSfpReset': grpc.unary_unary_rpc_method_handler(
          servicer.ReqSfpReset,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'GetSfpResetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpResetStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'ReqSfpLPMode': grpc.unary_unary_rpc_method_handler(
          servicer.ReqSfpLPMode,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'GetSfpLPStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpLPStatus,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'ReqSfpTxDisable': grpc.unary_unary_rpc_method_handler(
          servicer.ReqSfpTxDisable,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
      'GetSfpNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetSfpNum,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfpOpsPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfpOpsPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.XcvrPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class EepromPlatformNdkServiceStub(object):
  """Eeprom related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCardHwsku = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardHwsku',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardVendorName = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardVendorName',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardProductName = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardProductName',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardSerialNumber = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardSerialNumber',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardPartNumber = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardPartNumber',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardCleiNumber = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardCleiNumber',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardMfgDate = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardMfgDate',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardBaseMac = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardBaseMac',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardMacCount = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardMacCount',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetCardEepromAllTlvs = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetCardEepromAllTlvs',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )
    self.GetChassisEeprom = channel.unary_unary(
        '/protos.platform_ndk.EepromPlatformNdkService/GetChassisEeprom',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.FromString,
        )


class EepromPlatformNdkServiceServicer(object):
  """Eeprom related APIs
  """

  def GetCardHwsku(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardVendorName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardProductName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardSerialNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardPartNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardCleiNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardMfgDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardBaseMac(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardMacCount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCardEepromAllTlvs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChassisEeprom(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EepromPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCardHwsku': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardHwsku,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardVendorName': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardVendorName,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardProductName': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardProductName,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardSerialNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardSerialNumber,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardPartNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardPartNumber,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardCleiNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardCleiNumber,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardMfgDate': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardMfgDate,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardBaseMac': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardBaseMac,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardMacCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardMacCount,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetCardEepromAllTlvs': grpc.unary_unary_rpc_method_handler(
          servicer.GetCardEepromAllTlvs,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
      'GetChassisEeprom': grpc.unary_unary_rpc_method_handler(
          servicer.GetChassisEeprom,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqEepromInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespEepromInfoPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.EepromPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FirmwarePlatformNdkServiceStub(object):
  """//Firmware related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReqHwFirmwareVersion = channel.unary_unary(
        '/protos.platform_ndk.FirmwarePlatformNdkService/ReqHwFirmwareVersion',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqHwFirmwareInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespHwFirmwareInfoPb.FromString,
        )
    self.HwFirmwareGetComponents = channel.unary_unary(
        '/protos.platform_ndk.FirmwarePlatformNdkService/HwFirmwareGetComponents',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqHwFirmwareInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespHwFirmwareInfoPb.FromString,
        )


class FirmwarePlatformNdkServiceServicer(object):
  """//Firmware related APIs
  """

  def ReqHwFirmwareVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HwFirmwareGetComponents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FirmwarePlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReqHwFirmwareVersion': grpc.unary_unary_rpc_method_handler(
          servicer.ReqHwFirmwareVersion,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqHwFirmwareInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespHwFirmwareInfoPb.SerializeToString,
      ),
      'HwFirmwareGetComponents': grpc.unary_unary_rpc_method_handler(
          servicer.HwFirmwareGetComponents,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqHwFirmwareInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespHwFirmwareInfoPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.FirmwarePlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class UtilPlatformNdkServiceStub(object):
  """//Utility Platform related APIs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReqSfmInfo = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ReqSfmInfo',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqSfmInfoPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespSfmInfoPb.FromString,
        )
    self.ReqAdminTech = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ReqAdminTech',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqAdminTechPb.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ReqLogSetAll = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ReqLogSetAll',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.FromString,
        )
    self.ReqLogSetModule = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ReqLogSetModule',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.FromString,
        )
    self.ReqLogResetAll = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ReqLogResetAll',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.FromString,
        )
    self.ShowLogAll = channel.unary_unary(
        '/protos.platform_ndk.UtilPlatformNdkService/ShowLogAll',
        request_serializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.SerializeToString,
        response_deserializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.FromString,
        )


class UtilPlatformNdkServiceServicer(object):
  """//Utility Platform related APIs
  """

  def ReqSfmInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqAdminTech(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqLogSetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqLogSetModule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqLogResetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowLogAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UtilPlatformNdkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReqSfmInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ReqSfmInfo,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqSfmInfoPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespSfmInfoPb.SerializeToString,
      ),
      'ReqAdminTech': grpc.unary_unary_rpc_method_handler(
          servicer.ReqAdminTech,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqAdminTechPb.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ReqLogSetAll': grpc.unary_unary_rpc_method_handler(
          servicer.ReqLogSetAll,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.SerializeToString,
      ),
      'ReqLogSetModule': grpc.unary_unary_rpc_method_handler(
          servicer.ReqLogSetModule,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.SerializeToString,
      ),
      'ReqLogResetAll': grpc.unary_unary_rpc_method_handler(
          servicer.ReqLogResetAll,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.SerializeToString,
      ),
      'ShowLogAll': grpc.unary_unary_rpc_method_handler(
          servicer.ShowLogAll,
          request_deserializer=platform__ndk_dot_platform__ndk__pb2.ReqLogSettingPb.FromString,
          response_serializer=platform__ndk_dot_platform__ndk__pb2.RespLogSettingPb.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.platform_ndk.UtilPlatformNdkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
